rly_file = "Wrexham_to_Bidston.rly"
ttb_files = [ "Wrexham_to_Bidston.ttb",]
ssn_files = [ "Wrexham_to_Bidston_Pre_Start_autoimatic_signal_routes_set.ssn",]
img_files = [ "Wrexham_to_Bidston.bmp",]
doc_files = [ "README.md",]
release_date = "2020-09-23"
version = "1.0.0"
country_code = "GB"
factual = true
description = "Simulation of the area around Wrexham, Wales, UK."
year = 2020
display_name = "Wrexham_To_Bidston"
name = "Wrexham_To_Bidston"
signal_position = "left"
author = "markgajones"
contributors = []
